[build-system]
requires = ["maturin>=1.7,<2"]
build-backend = "maturin"

[project]
name = "lymapy"
version = "0.1.0"
description = "Python bindings for lyma and LYBA"
requires-python = ">=3.8"
license = { text = "MIT OR Apache-2.0" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Rust",
]

[tool.maturin]
features = ["python"]
module-name = "lymapy"

[tool.uv.workspace]
members = [
    "examples/python",
]

[[tool.uv.index]]
name = "lymapy"
url = "https://pypi.org/project/lymapy/"
