[package]
name = "luma-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
luma = { path = "..", features = ["parser", "syntax"] }
luma-parser = { path = "../crates/luma-parser" }
luma-syntax = { path = "../crates/luma-syntax" }

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "format"
path = "fuzz_targets/format.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
