[package]
name = "lyma-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
lyma = { path = "..", features = ["parser", "syntax"] }
lyma-lyba = { path = "../crates/lyma-lyba" }
lyma-parser = { path = "../crates/lyma-parser" }
lyma-syntax = { path = "../crates/lyma-syntax" }

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "format"
path = "fuzz_targets/format.rs"
test = false
doc = false
bench = false

[[bin]]
name = "lyba_read"
path = "fuzz_targets/lyba_read.rs"
test = false
doc = false
bench = false

[[bin]]
name = "lyba_value"
path = "fuzz_targets/lyba_value.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
