[package]
name = "luma-serde"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
luma-syntax = { path = "../luma-syntax" }
serde.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true
