[package]
name = "lyma-serde"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
lyma-syntax = { path = "../lyma-syntax" }
serde.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true
