[package]
name = "luma-engine-omnilua"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = []

[dependencies]
luma-runtime = { path = "../luma-runtime" }
luma-syntax = { path = "../luma-syntax" }
omnilua.workspace = true

[dev-dependencies]
luma-syntax = { path = "../luma-syntax" }

[[test]]
name = "omnilua-integration"
path = "../../tests/omnilua/integration.rs"

[lib]
path = "src/lib.rs"

[lints]
workspace = true
