//! Source file (`SRCF`) and source span (`SRCS`) helpers.

use crate::blob::{BlobId, BlobTable};
use crate::error::{ErrorContext, LybaError, Result};
use crate::policy::Limits;
use crate::primitives::UVar;
use crate::string_table::StringTable;

/// `SRCF`
pub const SOURCE_FILE_SECTION_NAME: &str = "SRCF";
/// `SRCS`
pub const SOURCE_SPAN_SECTION_NAME: &str = "SRCS";

/// Source URI is present.
pub const SOURCE_FILE_FLAG_URI_PRESENT: u64 = 1 << 0;
/// Display name is present.
pub const SOURCE_FILE_FLAG_DISPLAY_PRESENT: u64 = 1 << 1;
/// Embedded source blob reference is present.
pub const SOURCE_FILE_FLAG_SOURCE_BLOB_PRESENT: u64 = 1 << 2;
/// Digest blob reference is present.
pub const SOURCE_FILE_FLAG_DIGEST_PRESENT: u64 = 1 << 3;
/// Source is virtual and not backed by an external location.
pub const SOURCE_FILE_FLAG_VIRTUAL: u64 = 1 << 4;
/// Source is private and requires trusted reader policy.
pub const SOURCE_FILE_FLAG_PRIVATE: u64 = 1 << 5;
/// Source content was generated.
pub const SOURCE_FILE_FLAG_GENERATED: u64 = 1 << 6;
/// Reserved source-file flag bits.
pub const SOURCE_FILE_FLAG_RESERVED_MASK: u64 = !0x7f;

/// Span was generated by tooling.
pub const SOURCE_SPAN_FLAG_GENERATED: u64 = 1 << 0;
/// Span does not map directly to source bytes.
pub const SOURCE_SPAN_FLAG_SYNTHETIC: u64 = 1 << 1;
/// Span came from an include or assembly expansion.
pub const SOURCE_SPAN_FLAG_MACRO_OR_INCLUDE_EXPANSION: u64 = 1 << 2;
/// Span identifies source contributing to an evaluated expression result.
pub const SOURCE_SPAN_FLAG_EXPRESSION_RESULT: u64 = 1 << 3;
/// Reserved source-span flag bits.
pub const SOURCE_SPAN_FLAG_RESERVED_MASK: u64 = !0x0f;

/// One decoded `SRCF` record.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SourceFileRecord {
    /// Stored flags.
    pub flags: u64,
    /// Optional inert source URI stored through `STRS`.
    pub uri: Option<String>,
    /// Optional user-facing display string stored through `STRS`.
    pub display: Option<String>,
    /// Optional embedded source content blob reference into `BLOB`.
    pub source_blob_ref: Option<BlobId>,
    /// Optional source digest blob reference into `BLOB`.
    pub digest_blob_ref: Option<BlobId>,
}

impl SourceFileRecord {
    /// Creates an empty source-file record.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Sets explicit flags.
    #[must_use]
    pub fn with_flags(mut self, flags: u64) -> Self {
        self.flags = flags;
        self
    }

    /// Sets an optional inert source URI.
    #[must_use]
    pub fn with_uri(mut self, uri: Option<String>) -> Self {
        self.uri = uri;
        self
    }

    /// Sets an optional display string.
    #[must_use]
    pub fn with_display(mut self, display: Option<String>) -> Self {
        self.display = display;
        self
    }

    /// Sets an optional embedded source blob reference.
    #[must_use]
    pub fn with_source_blob_ref(mut self, source_blob_ref: Option<BlobId>) -> Self {
        self.source_blob_ref = source_blob_ref;
        self
    }

    /// Sets an optional digest blob reference.
    #[must_use]
    pub fn with_digest_blob_ref(mut self, digest_blob_ref: Option<BlobId>) -> Self {
        self.digest_blob_ref = digest_blob_ref;
        self
    }

    /// Returns whether a source URI is present.
    #[must_use]
    pub const fn has_uri(&self) -> bool {
        self.flags & SOURCE_FILE_FLAG_URI_PRESENT != 0
    }

    /// Returns whether a display string is present.
    #[must_use]
    pub const fn has_display(&self) -> bool {
        self.flags & SOURCE_FILE_FLAG_DISPLAY_PRESENT != 0
    }

    /// Returns whether an embedded source blob reference is present.
    #[must_use]
    pub const fn has_source_blob(&self) -> bool {
        self.flags & SOURCE_FILE_FLAG_SOURCE_BLOB_PRESENT != 0
    }

    /// Returns whether a digest blob reference is present.
    #[must_use]
    pub const fn has_digest(&self) -> bool {
        self.flags & SOURCE_FILE_FLAG_DIGEST_PRESENT != 0
    }

    /// Returns whether the source is virtual.
    #[must_use]
    pub const fn is_virtual(&self) -> bool {
        self.flags & SOURCE_FILE_FLAG_VIRTUAL != 0
    }

    /// Returns whether the source is private.
    #[must_use]
    pub const fn is_private(&self) -> bool {
        self.flags & SOURCE_FILE_FLAG_PRIVATE != 0
    }

    /// Returns whether the source is generated.
    #[must_use]
    pub const fn is_generated(&self) -> bool {
        self.flags & SOURCE_FILE_FLAG_GENERATED != 0
    }

    fn normalized_flags(&self) -> u64 {
        normalize_flags(
            self.flags,
            self.uri.is_some(),
            self.display.is_some(),
            self.source_blob_ref.is_some(),
            self.digest_blob_ref.is_some(),
        )
    }
}

/// In-memory `SRCF` table.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SourceFileTable {
    /// Ordered source-file records.
    pub records: Vec<SourceFileRecord>,
}

impl SourceFileTable {
    /// Creates an empty table.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Appends a record.
    #[must_use]
    pub fn with_record(mut self, record: SourceFileRecord) -> Self {
        self.records.push(record);
        self
    }

    /// Returns the record count.
    #[must_use]
    pub fn len(&self) -> usize {
        self.records.len()
    }

    /// Returns whether the table is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.records.is_empty()
    }
}

/// One decoded `SRCS` record.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct SourceSpanRecord {
    /// Zero-based source-file reference into `SRCF`.
    pub source_file_ref: u64,
    /// Zero-based UTF-8 byte offset into the source.
    pub byte_offset: u64,
    /// UTF-8 byte length of the half-open span.
    pub byte_length: u64,
    /// One-based starting line.
    pub start_line: u64,
    /// One-based starting column.
    pub start_column: u64,
    /// One-based ending line.
    pub end_line: u64,
    /// One-based ending column.
    pub end_column: u64,
    /// Stored raw span flags.
    pub flags: u64,
}

impl SourceSpanRecord {
    /// Creates a span record with required byte-range fields.
    #[must_use]
    pub fn new(source_file_ref: u64, byte_offset: u64, byte_length: u64) -> Self {
        Self {
            source_file_ref,
            byte_offset,
            byte_length,
            start_line: 1,
            start_column: 1,
            end_line: 1,
            end_column: 1,
            flags: 0,
        }
    }

    /// Sets the source-file reference.
    #[must_use]
    pub fn with_source_file_ref(mut self, source_file_ref: u64) -> Self {
        self.source_file_ref = source_file_ref;
        self
    }

    /// Sets the byte offset.
    #[must_use]
    pub fn with_byte_offset(mut self, byte_offset: u64) -> Self {
        self.byte_offset = byte_offset;
        self
    }

    /// Sets the byte length.
    #[must_use]
    pub fn with_byte_length(mut self, byte_length: u64) -> Self {
        self.byte_length = byte_length;
        self
    }

    /// Sets the one-based start position.
    #[must_use]
    pub fn with_start_position(mut self, line: u64, column: u64) -> Self {
        self.start_line = line;
        self.start_column = column;
        self
    }

    /// Sets the one-based end position.
    #[must_use]
    pub fn with_end_position(mut self, line: u64, column: u64) -> Self {
        self.end_line = line;
        self.end_column = column;
        self
    }

    /// Sets stored raw flags.
    #[must_use]
    pub fn with_flags(mut self, flags: u64) -> Self {
        self.flags = flags;
        self
    }

    /// Returns the exclusive end byte offset when it fits in `u64`.
    #[must_use]
    pub fn byte_end(&self) -> Option<u64> {
        self.byte_offset.checked_add(self.byte_length)
    }

    /// Returns whether the span is marked generated.
    #[must_use]
    pub const fn is_generated(&self) -> bool {
        self.flags & SOURCE_SPAN_FLAG_GENERATED != 0
    }

    /// Returns whether the span is marked synthetic.
    #[must_use]
    pub const fn is_synthetic(&self) -> bool {
        self.flags & SOURCE_SPAN_FLAG_SYNTHETIC != 0
    }

    /// Returns whether the span is marked as macro/include expansion.
    #[must_use]
    pub const fn is_macro_or_include_expansion(&self) -> bool {
        self.flags & SOURCE_SPAN_FLAG_MACRO_OR_INCLUDE_EXPANSION != 0
    }

    /// Returns whether the span is marked as an expression result.
    #[must_use]
    pub const fn is_expression_result(&self) -> bool {
        self.flags & SOURCE_SPAN_FLAG_EXPRESSION_RESULT != 0
    }

    /// Converts the stored byte range into a syntax-layer span when values fit.
    #[must_use]
    pub fn to_lyma_syntax_span(&self) -> Option<lyma_syntax::Span> {
        let file_id = u32::try_from(self.source_file_ref).ok()?;
        let start = usize::try_from(self.byte_offset).ok()?;
        let end = usize::try_from(self.byte_end()?).ok()?;
        Some(lyma_syntax::Span::new(
            lyma_syntax::FileId(file_id),
            start,
            end,
        ))
    }

    /// Converts the stored start position into a syntax-layer position when values fit.
    #[must_use]
    pub fn start_position_to_lyma_syntax(&self) -> Option<lyma_syntax::SourcePosition> {
        Some(lyma_syntax::SourcePosition {
            line: usize::try_from(self.start_line).ok()?,
            column: usize::try_from(self.start_column).ok()?,
        })
    }

    /// Converts the stored end position into a syntax-layer position when values fit.
    #[must_use]
    pub fn end_position_to_lyma_syntax(&self) -> Option<lyma_syntax::SourcePosition> {
        Some(lyma_syntax::SourcePosition {
            line: usize::try_from(self.end_line).ok()?,
            column: usize::try_from(self.end_column).ok()?,
        })
    }

    /// Builds a stored span record from syntax-layer span and positions when values fit.
    #[must_use]
    pub fn from_lyma_syntax(
        span: lyma_syntax::Span,
        start: lyma_syntax::SourcePosition,
        end: lyma_syntax::SourcePosition,
    ) -> Option<Self> {
        Some(
            Self::new(
                u64::from(span.file_id.0),
                u64::try_from(span.start).ok()?,
                u64::try_from(span.end.checked_sub(span.start)?).ok()?,
            )
            .with_start_position(
                u64::try_from(start.line).ok()?,
                u64::try_from(start.column).ok()?,
            )
            .with_end_position(
                u64::try_from(end.line).ok()?,
                u64::try_from(end.column).ok()?,
            ),
        )
    }
}

/// In-memory `SRCS` table.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct SourceSpanTable {
    /// Ordered source-span records.
    pub records: Vec<SourceSpanRecord>,
}

impl SourceSpanTable {
    /// Creates an empty table.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Appends a record.
    #[must_use]
    pub fn with_record(mut self, record: SourceSpanRecord) -> Self {
        self.records.push(record);
        self
    }

    /// Returns the record count.
    #[must_use]
    pub fn len(&self) -> usize {
        self.records.len()
    }

    /// Returns whether the table is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.records.is_empty()
    }
}

pub(crate) fn decode_source_file_table(
    payload: &[u8],
    limits: &Limits,
    strings: &StringTable,
    blob_count: usize,
) -> Result<SourceFileTable> {
    let mut offset = 0_usize;
    let source_count = usize::try_from(UVar::decode(payload, &mut offset)?.0)
        .map_err(|_| LybaError::limit_exceeded("source file count exceeds configured maximum"))?;
    if source_count > limits.max_table_record_count {
        return Err(LybaError::limit_exceeded(
            "source file count exceeds configured maximum",
        ));
    }

    let mut records = Vec::with_capacity(source_count);
    for record_index in 0..source_count {
        let flags_offset = offset;
        let flags = UVar::decode(payload, &mut offset)?.0;
        if flags & SOURCE_FILE_FLAG_RESERVED_MASK != 0 {
            return Err(LybaError::InvalidReservedFlags(
                ErrorContext::new("reserved source file flag bits were non-zero")
                    .with_byte_offset(flags_offset)
                    .with_record_index(record_index),
            ));
        }
        let uri = decode_string_ref(payload, &mut offset, strings, record_index, "source URI")?;
        let display = decode_string_ref(
            payload,
            &mut offset,
            strings,
            record_index,
            "source display",
        )?;
        let source_blob_ref = decode_blob_ref(
            payload,
            &mut offset,
            blob_count,
            record_index,
            "source blob",
        )?;
        let digest_blob_ref = decode_blob_ref(
            payload,
            &mut offset,
            blob_count,
            record_index,
            "source digest",
        )?;

        records.push(SourceFileRecord {
            flags: normalize_flags(
                flags,
                uri.is_some(),
                display.is_some(),
                source_blob_ref.is_some(),
                digest_blob_ref.is_some(),
            ),
            uri: uri.map(|string_id| strings.strings[string_id as usize].value.clone()),
            display: display.map(|string_id| strings.strings[string_id as usize].value.clone()),
            source_blob_ref: source_blob_ref.map(BlobId),
            digest_blob_ref: digest_blob_ref.map(BlobId),
        });
    }

    if offset != payload.len() {
        return Err(LybaError::InvalidSectionTable(
            ErrorContext::new("source file table payload had trailing bytes")
                .with_byte_offset(offset),
        ));
    }

    Ok(SourceFileTable { records })
}

pub(crate) fn encode_source_file_table(
    table: &SourceFileTable,
    strings: &StringTable,
    blob_count: usize,
) -> Result<Vec<u8>> {
    let mut bytes = Vec::new();
    UVar(table.records.len() as u64).encode_into(&mut bytes);

    for (record_index, record) in table.records.iter().enumerate() {
        let flags = record.normalized_flags();
        if flags & SOURCE_FILE_FLAG_RESERVED_MASK != 0 {
            return Err(LybaError::InvalidReservedFlags(
                ErrorContext::new("reserved source file flag bits were non-zero")
                    .with_record_index(record_index),
            ));
        }

        UVar(flags).encode_into(&mut bytes);
        UVar(encode_string_ref(
            record.uri.as_deref(),
            strings,
            record_index,
            "source URI",
        )?)
        .encode_into(&mut bytes);
        UVar(encode_string_ref(
            record.display.as_deref(),
            strings,
            record_index,
            "source display",
        )?)
        .encode_into(&mut bytes);
        UVar(encode_blob_ref(
            record.source_blob_ref,
            blob_count,
            record_index,
            "source blob",
        )?)
        .encode_into(&mut bytes);
        UVar(encode_blob_ref(
            record.digest_blob_ref,
            blob_count,
            record_index,
            "source digest",
        )?)
        .encode_into(&mut bytes);
    }

    Ok(bytes)
}

pub(crate) fn decode_source_span_table(
    payload: &[u8],
    limits: &Limits,
    source_files: &SourceFileTable,
    blobs: Option<&BlobTable>,
) -> Result<SourceSpanTable> {
    let mut offset = 0_usize;
    let span_count = usize::try_from(UVar::decode(payload, &mut offset)?.0)
        .map_err(|_| LybaError::limit_exceeded("source span count exceeds configured maximum"))?;
    if span_count > limits.max_table_record_count {
        return Err(LybaError::limit_exceeded(
            "source span count exceeds configured maximum",
        ));
    }

    let mut records = Vec::with_capacity(span_count);
    for record_index in 0..span_count {
        let source_file_ref = decode_source_file_ref(
            payload,
            &mut offset,
            source_files.records.len(),
            record_index,
        )?;
        let byte_offset = decode_uvar(payload, &mut offset)?;
        let byte_length = decode_uvar(payload, &mut offset)?;
        let start_line = decode_uvar(payload, &mut offset)?;
        let start_column = decode_uvar(payload, &mut offset)?;
        let end_line = decode_uvar(payload, &mut offset)?;
        let end_column = decode_uvar(payload, &mut offset)?;
        let flags_offset = offset;
        let flags = decode_uvar(payload, &mut offset)?;

        let record = SourceSpanRecord {
            source_file_ref,
            byte_offset,
            byte_length,
            start_line,
            start_column,
            end_line,
            end_column,
            flags,
        };
        validate_source_span_record(
            &record,
            source_files,
            blobs,
            record_index,
            Some(flags_offset),
        )?;
        records.push(record);
    }

    if offset != payload.len() {
        return Err(LybaError::InvalidSectionTable(
            ErrorContext::new("source span table payload had trailing bytes")
                .with_byte_offset(offset),
        ));
    }

    Ok(SourceSpanTable { records })
}

pub(crate) fn encode_source_span_table(
    table: &SourceSpanTable,
    limits: &Limits,
    source_files: &SourceFileTable,
    blobs: Option<&BlobTable>,
) -> Result<Vec<u8>> {
    if table.records.len() > limits.max_table_record_count {
        return Err(LybaError::limit_exceeded(
            "source span count exceeds configured maximum",
        ));
    }

    let mut bytes = Vec::new();
    UVar(table.records.len() as u64).encode_into(&mut bytes);

    for (record_index, record) in table.records.iter().enumerate() {
        validate_source_span_record(record, source_files, blobs, record_index, None)?;
        UVar(record.source_file_ref).encode_into(&mut bytes);
        UVar(record.byte_offset).encode_into(&mut bytes);
        UVar(record.byte_length).encode_into(&mut bytes);
        UVar(record.start_line).encode_into(&mut bytes);
        UVar(record.start_column).encode_into(&mut bytes);
        UVar(record.end_line).encode_into(&mut bytes);
        UVar(record.end_column).encode_into(&mut bytes);
        UVar(record.flags).encode_into(&mut bytes);
    }

    Ok(bytes)
}

fn normalize_flags(
    flags: u64,
    has_uri: bool,
    has_display: bool,
    has_source_blob: bool,
    has_digest: bool,
) -> u64 {
    let mut flags = flags;
    if has_uri {
        flags |= SOURCE_FILE_FLAG_URI_PRESENT;
    } else {
        flags &= !SOURCE_FILE_FLAG_URI_PRESENT;
    }
    if has_display {
        flags |= SOURCE_FILE_FLAG_DISPLAY_PRESENT;
    } else {
        flags &= !SOURCE_FILE_FLAG_DISPLAY_PRESENT;
    }
    if has_source_blob {
        flags |= SOURCE_FILE_FLAG_SOURCE_BLOB_PRESENT;
    } else {
        flags &= !SOURCE_FILE_FLAG_SOURCE_BLOB_PRESENT;
    }
    if has_digest {
        flags |= SOURCE_FILE_FLAG_DIGEST_PRESENT;
    } else {
        flags &= !SOURCE_FILE_FLAG_DIGEST_PRESENT;
    }
    flags
}

fn decode_string_ref(
    payload: &[u8],
    offset: &mut usize,
    strings: &StringTable,
    record_index: usize,
    kind: &str,
) -> Result<Option<u64>> {
    let encoded = UVar::decode(payload, offset)?.0;
    if encoded == 0 {
        return Ok(None);
    }
    let string_ref = encoded - 1;
    if string_ref >= strings.strings.len() as u64 {
        return Err(LybaError::InvalidValueReference(
            ErrorContext::new(format!("{kind} string reference was out of range"))
                .with_record_index(record_index),
        ));
    }
    Ok(Some(string_ref))
}

fn encode_string_ref(
    value: Option<&str>,
    strings: &StringTable,
    record_index: usize,
    kind: &str,
) -> Result<u64> {
    let Some(value) = value else {
        return Ok(0);
    };
    strings
        .strings
        .iter()
        .position(|record| record.value == value)
        .ok_or_else(|| {
            LybaError::InvalidValueReference(
                ErrorContext::new(format!("{kind} string was not present in STRS"))
                    .with_record_index(record_index),
            )
        })
        .and_then(|index| {
            u64::try_from(index)
                .ok()
                .and_then(|index| index.checked_add(1))
                .ok_or_else(|| {
                    LybaError::invalid_section_table("source string reference overflowed u64")
                })
        })
}

fn decode_blob_ref(
    payload: &[u8],
    offset: &mut usize,
    blob_count: usize,
    record_index: usize,
    kind: &str,
) -> Result<Option<u64>> {
    let encoded = UVar::decode(payload, offset)?.0;
    if encoded == 0 {
        return Ok(None);
    }
    let blob_ref = encoded - 1;
    if blob_ref >= blob_count as u64 {
        return Err(LybaError::InvalidValueReference(
            ErrorContext::new(format!("{kind} reference was out of range"))
                .with_record_index(record_index),
        ));
    }
    Ok(Some(blob_ref))
}

fn encode_blob_ref(
    blob_ref: Option<BlobId>,
    blob_count: usize,
    record_index: usize,
    kind: &str,
) -> Result<u64> {
    let Some(blob_ref) = blob_ref else {
        return Ok(0);
    };
    if blob_ref.0 >= blob_count as u64 {
        return Err(LybaError::InvalidValueReference(
            ErrorContext::new(format!("{kind} reference was out of range"))
                .with_record_index(record_index),
        ));
    }
    blob_ref
        .0
        .checked_add(1)
        .ok_or_else(|| LybaError::invalid_section_table("source blob reference overflowed u64"))
}

fn validate_source_span_record(
    record: &SourceSpanRecord,
    source_files: &SourceFileTable,
    blobs: Option<&BlobTable>,
    record_index: usize,
    flags_offset: Option<usize>,
) -> Result<()> {
    if record.flags & SOURCE_SPAN_FLAG_RESERVED_MASK != 0 {
        let context = ErrorContext::new("reserved source span flag bits were non-zero")
            .with_record_index(record_index);
        let context = if let Some(flags_offset) = flags_offset {
            context.with_byte_offset(flags_offset)
        } else {
            context
        };
        return Err(LybaError::InvalidReservedFlags(context));
    }
    if record.start_line == 0
        || record.start_column == 0
        || record.end_line == 0
        || record.end_column == 0
    {
        return Err(LybaError::InvalidSourceSpan(
            ErrorContext::new("source span lines and columns must be one-based")
                .with_record_index(record_index),
        ));
    }
    let source_file_index = usize::try_from(record.source_file_ref).map_err(|_| {
        LybaError::InvalidValueReference(
            ErrorContext::new("source span source file reference exceeded platform limits")
                .with_record_index(record_index),
        )
    })?;
    let source_file = source_files.records.get(source_file_index).ok_or_else(|| {
        LybaError::InvalidValueReference(
            ErrorContext::new(format!(
                "source span source file reference {} was out of range for SRCF count {}",
                record.source_file_ref,
                source_files.records.len()
            ))
            .with_record_index(record_index),
        )
    })?;
    let byte_end = record.byte_end().ok_or_else(|| {
        LybaError::InvalidSourceSpan(
            ErrorContext::new("source span byte range overflowed").with_record_index(record_index),
        )
    })?;

    if let (Some(blob_ref), Some(blobs)) = (source_file.source_blob_ref, blobs) {
        let blob = blobs.get(blob_ref).ok_or_else(|| {
            LybaError::InvalidValueReference(
                ErrorContext::new(format!(
                    "source span referenced embedded source blob {} that was not present",
                    blob_ref.0
                ))
                .with_record_index(record_index),
            )
        })?;
        let blob_len = u64::try_from(blob.len()).unwrap_or(u64::MAX);
        if byte_end > blob_len {
            return Err(LybaError::InvalidSourceSpan(
                ErrorContext::new(format!(
                    "source span byte range {}..{} was outside embedded source length {}",
                    record.byte_offset, byte_end, blob_len
                ))
                .with_record_index(record_index),
            ));
        }
    }

    Ok(())
}

fn decode_source_file_ref(
    payload: &[u8],
    offset: &mut usize,
    source_count: usize,
    record_index: usize,
) -> Result<u64> {
    let source_file_ref = decode_uvar(payload, offset)?;
    let source_file_index = usize::try_from(source_file_ref).map_err(|_| {
        LybaError::InvalidValueReference(
            ErrorContext::new("source span source file reference exceeded platform limits")
                .with_record_index(record_index),
        )
    })?;
    if source_file_index >= source_count {
        return Err(LybaError::InvalidValueReference(
            ErrorContext::new(format!(
                "source span source file reference {source_file_ref} was out of range for SRCF count {source_count}"
            ))
            .with_record_index(record_index),
        ));
    }
    Ok(source_file_ref)
}

fn decode_uvar(payload: &[u8], offset: &mut usize) -> Result<u64> {
    Ok(UVar::decode(payload, offset)?.0)
}
